### ISSUE TITLE
Live preview vs. actual markdown formatting mismatch

### ISSUE THREAD

**Issue by relikd** [glushchenko/fsnotes#1065]
**Describe the bug**
Styling (like underscores) inside code environment is applied to text outside of the environment.

**To Reproduce**
```
replace `_10` with `_1`
```

**Expected behavior**
The code environment should ignore all markdown commands until the environment is closed.

**Actual behavior**
See image. The with in between shouldn't be italic in the live preview.

**Workaround**
None. ... Actually thats funny and leads me to another bug: `\_hi there\_` should escapte the underscore and print the text without italics, however the live preview still shows formatting (see screen2)

**Supporting Files**
![screen](https://user-images.githubusercontent.com/1321720/106448835-964c2c80-6483-11eb-8d88-e0d217f4b16d.png)
![screen2](https://user-images.githubusercontent.com/1321720/106448845-98ae8680-6483-11eb-915d-db6f9dda6d8d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - OS version: 10.15.7
 - FSNotes version: 4.9.5

**Additional context**
NA

**Comment by glushchenko** [comment]
Fixed in 4.9.6 https://github.com/glushchenko/fsnotes/releases/download/4.9.6/FSNotes.zip

**Comment by relikd** [comment]
A small addendum, the underscore "hi there" example is still rendered italic in the live preview, even though it shouldn't.

**Comment by glushchenko** [comment]
Live preview implemented by libcmark_gfm and should be addressed to https://github.com/github/cmark-gfm

**Comment by relikd** [comment]
Isnt cmark just the normal preview? I speak of the live preview you see before hitting the preview button. E.g., you fixed it for the "with" in the example above, but the "hi there" is on the same page but not fixed.

**Comment by glushchenko** [comment]
"hi there" escaping by slash is in markdown spec?

**Comment by relikd** [comment]
at least in the cmark specs, yes. And github supports it, eg.: \_here\_ (<-- `\_here\_`)

**Comment by glushchenko** [comment]
Fixed!

**Comment by glushchenko** [comment]
https://github.com/glushchenko/fsnotes/releases/download/4.9.7beta/FSNotes.zip
