### ISSUE TITLE
Deleted notes don't remain deleted....

### ISSUE THREAD

**Issue by Marksur** [glushchenko/fsnotes#306]
After deleting a note, quitting FS Notes, then relaunching app, the deleted notes reappear.

**Comment by glushchenko** [comment]
Please describe steps to reproduce this bug. I am trying but in my environment notes removes properly.

**Comment by Marksur** [comment]
On my ipad, iphone and Mac i choose the note slide it to the left where i see the trash icon. I click on the trash icon and confirm that i want to delete it….It deletes fine. Now if i quite FS and relaunch it, the notes are still there, on all devices.


Mark
-------------------------

Mark Surloff
Photography of Architecture
1655 NE 115 St., Suite 33B
Miami, Fl 33181

cell: 305-527-4142
fax: 888-410-1731
email: mark@surloff.com
web site: http://www.surloff.com

**Comment by jeff-h** [comment]
That's really odd — the notes delete as expected for me (on Mac — haven't tried it on iOS).

**Comment by Marksur** [comment]
Sorry, I forgot to mention I’m running Mojave (beta). This may be the source of my problem.

**Comment by gingerbeardman** [comment]
are you running betas on your ios devices? I don't think iCloud syncs between beta and non-beta versions?

**Comment by Marksur** [comment]
No IOS betas...they do sync however.

**Comment by gingerbeardman** [comment]
The thing is, FS notes spent do any syncing. It just stores follow in iCloud and leaves that to get on with things

**Comment by Marksur** [comment]
yes...

**Comment by glushchenko** [comment]
Fixed

**Comment by sven-gh** [comment]
It seems random so don't know how to reproduce but have seen this happen numerous times:

delete a note in folder A > note is deleted
go to folder B
go back to folder A > the note you just deleted has reappeared (if you check the filesystem, the note does not exist so it did get deleted but the app is still showing it)

solution: when you relaunch the app, the deleted note will no longer show anywhere
