### ISSUE TITLE
Undo/redo disabled

### ISSUE THREAD

**Issue by bonny** [glushchenko/fsnotes#464]
I'm running version 2.6.0 (215) on MacOS Mojave 10.14.2 and the undo/redo menu choice is greyed out/disabled. Also cmd+z is not working. I'm pretty sure that undo did work in the past, because I make a lot of mistakes while typing so I undo a lot ;)

<img width="247" alt="screenshot 2019-01-18 at 14 56 21" src="https://user-images.githubusercontent.com/221570/51391032-4797f800-1b31-11e9-8f60-6c5e7f54756c.png">

**Comment by peavine** [comment]
I've found that undo works on some occasions but not others. I don't know why that is but will see if I can narrow that down.

**Comment by jeff-h** [comment]
Fixed in 2.7.0 :) Thanks @glushchenko!

**Comment by peavine** [comment]
I installed 2.7.0 and the undo command does not undo moving a note to the trash. I tried both undo from the top menu and the Control-Z shortcut. Am I doing something wrong?

**Comment by jeff-h** [comment]
Oh sorry — I only tried the undo/redo inside the editor.

**Comment by keymasterr** [comment]
Not fixed yet. 2.7.1 — undo/redo in editor still working weird, especially with tab spacing.

**Comment by glushchenko** [comment]
Sorry for this, guys. Now undo should working more reliable.

**Comment by jeff-h** [comment]
Thanks for all your work on this.

Just one further request - it would be nice if cut/copy/paste worked when you're editing a note's title.
