### ISSUE TITLE
Locked notes from desktop crash mobile app

### ISSUE THREAD

**Issue by olbrew** [glushchenko/fsnotes#672]
**Describe the bug**
When locking a note on the desktop app and then trying to open that same note on the mobile app it crashes immediately.

**To Reproduce**
1. Lock a note on the Desktop
2. Try to open the locked note by pressing it in the mobile app after it has synced
3. Mobile app crashes

**Expected behavior**
App uses TouchID/FaceID or asks for password to authenticate user.
After successful authentication the note unlocks and opens.

**Actual behavior**
App immediately crashes on opening locked notes.

**Desktop (please complete the following information):**
 - OS: MacOS, iOS
 - OS version: MacOS: Last stable as of now (10.14.6) and earlier, iOS Last stable as of now (12.4) and earlier
 - FSNotes version: MacOS: 3.4.0 and earlier, iOS:  2.9.0 and earlier

**Comment by glushchenko** [comment]
Sorry for delayed response. Bug fixed, but update blocked by App Store Team :-(

**Comment by glushchenko** [comment]
I think fixed in 3.0.1

**Comment by olbrew** [comment]
You mean the desktop version? The problem occurred with the mobile app crashing.
Unfortunately it still does as of the latest available version 3.0.1

**Comment by glushchenko** [comment]
Plea

**Comment by olbrew** [comment]
Sorry for the later reply but it's still occurring for me on a newly created note on FSNotes desktop (version 4.17), locking it with a password and then trying to reopen it on FSNotes iOS (version 3.1.5). Can you try to reproduce this?
